name: 'DevOps Pipeline'
on:
  pull_request:
  push:
   branches:
    - master
jobs:
  main:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout Source Code'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: 'Fetch master'
      if: github.ref != 'refs/heads/master'
      run: git branch master origin/master

    - name: 'Install Dependencies'
      run: npm ci

    - name: 'Run Static checking'
      run: npm run lint

    - name: 'Build'
      run: npm run build

    - name: 'Test'
      run: npm run coverage

    - name: 'Upload Build Quality'
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{github.workspace}}/packages/*/coverage/lcov.info:lcov

    - name: 'Prune Dependencies'
      run: npm run prune

    - name: 'Release'
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Deploy'
      if: github.ref == 'refs/heads/master'
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/1228409/gestao-contratos'
        azure-pipeline-name: 'tecidosbr.gestao-contratos'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
